apiVersion: apps/v1
kind: Deployment
metadata:
  creatingTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 5
  template:
    spec: 
      $setElementOrder/containers:
      - name: vote
      containers:
      - image: schoolofdevops/vote:v1
        name: vote
        envFrom:
          - configMapRef:
              name: vote-options
              optional: true
